ASFLAGS_ADDITIONAL = -c -g -DF_CPU=48000000L -DARDUINO=10801 -DARDUINO_SAMD_MKRWIFI1010 -DARDUINO_ARCH_SAMD  -D__SAMD21G18A__ -DUSB_VID=0x2341 -DUSB_PID=0x8054 -DUSBCON -DUSB_MANUFACTURER=\""Unknown\"" -DUSB_PRODUCT=\""Arduino MKR WiFi 1010\"" -D_RUNONTARGETHARDWARE_BUILD_ -D_ROTH_MKRWIFI1010_
TARGET_LOAD_CMD = 
TARGET_LOAD_CMD_ARGS = 
TARGET_PKG_INSTALLDIR = /Users/emiliendurif/Documents/MATLAB/SupportPackages/R2019b/toolbox/target/supportpackages/arduinotarget/registry/..
STACK_SIZE = 64
